# Generated by Django 4.0 on 2023-07-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clinic_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('doctor_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('drug_allergy', models.CharField(max_length=150)),
                ('id_person', models.CharField(max_length=150)),
                ('career', models.CharField(max_length=150)),
                ('address_current', models.CharField(max_length=150)),
                ('name_company', models.CharField(max_length=150)),
                ('tel_emergency', models.CharField(max_length=150)),
                ('note', models.CharField(max_length=150)),
                ('sickdisease', models.CharField(max_length=150)),
                ('image_sick', models.ImageField(blank=True, upload_to='image')),
                ('sick_status', models.CharField(default=0, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('credit_card', models.CharField(max_length=100)),
                ('pay_check', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('pay_status', models.IntegerField(default=0)),
                ('input_1', models.CharField(blank=True, max_length=100)),
                ('input_2', models.CharField(blank=True, max_length=100)),
                ('input_3', models.CharField(blank=True, max_length=100)),
                ('doctor_1', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.data')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('order_number', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('credit_card', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_count', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_qty', models.IntegerField()),
                ('shop_ps', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('shop_count', models.CharField(max_length=100)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Save_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sick_data', models.CharField(max_length=150)),
                ('sick_data', models.CharField(max_length=150)),
                ('person_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.data')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('sum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('user_doctor', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.shop_product')),
            ],
        ),
    ]
