# Generated by Django 4.0 on 2023-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='user_doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
